# Generated by Django 5.0.1 on 2024-02-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone_number',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
