<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-21 08:05
=======
# Generated by Django 5.0.1 on 2024-02-21 07:44
>>>>>>> dadaffef1d673510062569035cc5e4d9818ae8b0

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_user_email", models.CharField(max_length=300)),
                ("study_todo", models.CharField(max_length=300)),
                ("study_duration", models.DurationField(default="00:00:00")),
                ("study_completed", models.BooleanField(default=False)),
                ("study_status", models.TimeField(auto_now_add=True)),
                ("study_description", models.CharField(max_length=300)),
=======

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_user_email', models.CharField(max_length=300)),
                ('study_todo', models.CharField(max_length=300)),
                ('study_duration', models.DurationField(default=0)),
                ('study_completed', models.BooleanField(default=False)),
                ('study_status', models.TimeField(auto_now_add=True)),
                ('study_description', models.CharField(max_length=300)),
>>>>>>> dadaffef1d673510062569035cc5e4d9818ae8b0
            ],
        ),
    ]
