# Generated by Django 5.0.1 on 2024-02-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
